### PR TITLE
Project: HTML - Forms

### PR DESCRIPTION
**Pull request by SofiBretz**
Pulling the development project. For a code review.

### CODE REVIEW

**Comment by maelfosso** [comment]
Hello,

- [ ] Your README should be improved. Please add a description, the author's names and the link to their Github account and the link to the live version

- [x] Correct errors from https://validator.w3.org

- [ ] Remove the `<div class="formText">` from the `<form>`. Do the same thing with `<div class="termsText">`

- [ ] I encourage you to use of the `<main>` tag for the dominant content. Also for the `<header>`

Kindle make those changes and submit a new code review request.

**Comment by SofiBretz** [comment]
Dear Mael,

How are you? with respect of your correction: "Remove the <div
class="formText"> from the <form>. Do the same thing with <div
class="termsText">" we are not agree about doing this, because we applied
CSS styles to those specific classes, and if we remove them the text looks
bad. Otherwise, everything is fixed as you suggested. Thank you!

Regards,

Sofia Barrantes and Vladimir Luna.

**Comment by Torres-ssf** [comment]
### Nice job @SofiBretz @noomdalv 👏
I must say, your project looks great. You folks really did well. 

I think Mael asked you to remove those div tags because div has no semantic meaning, and for that reason, it's not a good practice to overusing it(not saying that you did that). But in the case of your project, there is a very easy approach to get rid of them and maintain the styles. What I would do is make class="formText" a `header` tag and class="termsText" a `footer`. You could also make the class="titleForm" a `h2` or `h3` tag instead. These changes would make your code even better in terms of semantic value, and semantic is a very important topic in HTML. But you a free to make these changes only if you want to.

One important thing though, the proper value for the attribute `type` for the phone input is `tel`, you can check all valid values here: https://www.w3schools.com/html/html_form_input_types.asp. This change is required by Microverse guidelines, but I trust you to do that before merging to master. So no need to submit this project for code review again.

Don't forget to submit the form. Good luck with the next project 😄.

**Comment by noomdalv** [comment]
Hi Sergio! Thank you so much for your feedback, we appreciate it 🙂

Regarding the semantic of the containers, we chose "formText" and
"termsText" as classes to specifically refer to the "Form Main Text" and
the "Form Terms and Conditions Text" respectively.
Maybe we need to be more specific and rename them to "formTopText" and
formBottomText", that way it will have better semantic value?
We tried our best to make the project looks as similar as possible to the
original page, since we didnt have the original font, we had to adapt and
style almost every text line with css.

As for the <header> and <footer> suggestions, maybe im wrong but the
general convention says those tags are unique and should be used
accordingly(header for the top content of the page and footer for bottom),
and since we are styling a form that is inside <main>, i think its not
appropiate 😅

We will be doing these changes as soon as possible and submitting the
project form, thanks again!!!

**Comment by Torres-ssf** [comment]
Hi there @noomdalv 
Your classes names are good, no problem with them at all. But when I talked about semantic I wasn't talking related to the classes names. Semantic in HTML is related to the use of the HTML5 tags. Semantic tags make it clear to the browser what the meaning of a page and its content is. That clarity is also communicated with search engines, ensuring that the right pages are delivered for the right queries. Screen readers use HTML5 tags to understand better your page and them deliver the information for the user(commonly a visually impaired person). 

Sorry, but I never saw this convention. It's actually a very common approach to use header and footer tags for specifying a header of a section and the footer of a section. In W3 schools, for example, https://www.w3schools.com/tags/tag_header.asp it says that you can have several headers in one document. If you check here in https://developer.mozilla.org/en-US/docs/Web/HTML/Element/header, you can see that all flow content(form is one of them) is allowed as a parent for header. A very common case it's to use the footer tag inside an article tag to list all related articles from that one.

**Comment by noomdalv** [comment]
You are right my friend, i guess i learned something new today! thanks!!

**Pull request merged**
